### ISSUE TITLE
literal

### ISSUE THREAD

**Issue by NickErmak** [compalex/tasks-performance#70]
https://github.com/compalex/tasks-performance/blob/1d539f5ff3bff06c7aab0b7a9bbe5fd38d668169/myTasks/src/myTasks/Task4.java#L20 use constants for your formats

**Comment by compalex** [comment]
no literals even if it's "printf"?! It'll be like s1+"%d" + s2 + "%d" + s3... u think that's better?

**Comment by NickErmak** [comment]
Use %d within the same string. Printf uses standard string.format
