### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by NickErmak** [compalex/tasks-performance#72]
https://github.com/compalex/tasks-performance/blob/1d539f5ff3bff06c7aab0b7a9bbe5fd38d668169/myTasks/src/myTasks/Task5.java#L17 StringBuilders method returns current object of StringBuilder. you can use its constructor with string param as well. More styled version:
	String input = getWord();
    	String reversedInput = new StringBuilder(input).reverse().toString();       
        System.out.println(QUESTION + input.equals(reversedInput));

Not just copy! Try to understand what is going on

**Comment by compalex** [comment]
ctrl+C & ctrl+V
